# Generated by Django 4.2.1 on 2023-05-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("main", "주요"),
                            ("festival", "축제"),
                            ("event", "이벤트"),
                            ("etc", "기타"),
                        ],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
