# Generated by Django 4.2.1 on 2023-05-15 18:04

import booth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=booth.models.image_upload_path
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Booth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "type",
                    models.CharField(
                        choices=[("", ""), ("", ""), ("", ""), ("", "")], max_length=4
                    ),
                ),
                ("operator", models.CharField(max_length=20)),
                ("start_at", models.DateTimeField(blank=True, null=True)),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("", ""),
                            ("", ""),
                            ("", ""),
                            ("", ""),
                            ("", ""),
                            ("", ""),
                            ("", ""),
                            ("", ""),
                            ("", ""),
                            ("", ""),
                            ("", ""),
                            ("", ""),
                        ],
                        max_length=4,
                    ),
                ),
                ("description", models.CharField(max_length=30)),
                ("menu", models.JSONField(default="{}")),
                ("concept", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="NotificationImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="notification.notification",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MenuImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booth",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="booth.booth"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LogoImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booth",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="booth.booth"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        blank=True,
                        default=booth.models.create_random_number,
                        editable=False,
                        max_length=10,
                    ),
                ),
                (
                    "booth",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="booth.booth"
                    ),
                ),
            ],
        ),
    ]
