# Generated by Django 4.2.1 on 2023-05-16 04:43

import booth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("주간부스", "주간부스"),
                            ("야간부스", "야간부스"),
                            ("플리마켓", "플리마켓"),
                            ("푸드트럭", "푸드트럭"),
                        ],
                        max_length=10,
                    ),
                ),
                ("operator", models.CharField(max_length=20)),
                ("start_at", models.DateField(blank=True, null=True)),
                ("end_at", models.DateField(blank=True, null=True)),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("이해랑예술극장", "이해랑예술극장"),
                            ("나체밭", "나체밭"),
                            ("사회과학관", "사회과학관"),
                            ("혜화관", "혜화관"),
                            ("혜화별관", "혜화별관"),
                            ("법학관", "법학관"),
                            ("명진관", "명진관"),
                            ("본관", "본관"),
                            ("만해광장", "만해광장"),
                            ("학생회관", "학생회관"),
                            ("학림관", "학림관"),
                        ],
                        max_length=10,
                    ),
                ),
                ("description", models.CharField(max_length=30)),
                ("menu", models.JSONField(default=dict)),
                ("concept", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("writer", models.CharField(max_length=30)),
                ("content", models.TextField()),
                ("password", models.PositiveSmallIntegerField()),
                ("ip_address", models.CharField(max_length=100)),
                ("is_deleted", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "booth",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="booth.booth"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        blank=True,
                        default=booth.models.create_random_number,
                        editable=False,
                        max_length=10,
                    ),
                ),
                (
                    "booth",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="booth.booth"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommentReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("writer", models.CharField(max_length=30)),
                ("content", models.TextField()),
                ("password", models.PositiveSmallIntegerField()),
                ("ip_address", models.CharField(max_length=100)),
                ("is_deleted", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="booth.comment"
                    ),
                ),
            ],
        ),
    ]
