# Generated by Django 4.2.1 on 2023-05-17 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("booth", "0002_menuimage_logoimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="like",
            name="booth",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="booth.booth",
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="key",
            field=models.CharField(
                blank=True, default="@*wz4C3{yK", editable=False, max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="logoimage",
            name="booth",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logoimages",
                to="booth.booth",
            ),
        ),
    ]
