# Generated by Django 4.2.1 on 2023-05-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booth", "0002_alter_booth_menu"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booth", name="menu", field=models.JSONField(default=dict),
        ),
    ]
