# Generated by Django 4.2.1 on 2023-05-17 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("booth", "0003_alter_like_booth_alter_like_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="like",
            name="key",
            field=models.CharField(
                blank=True, default="U*q?yq'pBp", editable=False, max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="menuimage",
            name="booth",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menuimages",
                to="booth.booth",
            ),
        ),
    ]
