# Generated by Django 4.2.1 on 2023-05-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booth", "0005_alter_like_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="commentreply",
            name="created_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="commentreply",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="like",
            name="key",
            field=models.CharField(
                blank=True, default="(2p=]<(y=}", editable=False, max_length=10
            ),
        ),
    ]
