# Generated by Django 4.2.1 on 2023-05-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booth", "0006_alter_like_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="password",
            field=models.PositiveSmallIntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name="commentreply",
            name="password",
            field=models.PositiveSmallIntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name="like",
            name="key",
            field=models.CharField(blank=True, editable=False, max_length=10),
        ),
    ]
