# Generated by Django 4.2.1 on 2023-05-18 06:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("booth", "0006_alter_comment_created_at_alter_comment_is_deleted_and_more"),
        ("booth", "0006_alter_like_key"),
    ]

    operations = []
