# Generated by Django 4.2.1 on 2023-05-18 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0007_merge_20230518_0641'),
        ('booth', '0008_alter_comment_password_alter_commentreply_password'),
    ]

    operations = [
    ]
