# Generated by Django 4.2.1 on 2023-05-18 17:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("booth", "0009_merge_20230518_0653"),
        ("booth", "0009_merge_20230518_1503"),
    ]

    operations = []
