# Generated by Django 4.2.1 on 2023-05-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booth", "0010_merge_20230518_1700"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booth",
            name="description",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="like",
            name="key",
            field=models.CharField(blank=True, editable=False, max_length=10),
        ),
    ]
