# Generated by Django 4.1 on 2023-05-20 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0011_alter_booth_description_alter_like_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='booth',
            name='section',
            field=models.CharField(default=1, max_length=5),
        ),
        migrations.AlterField(
            model_name='booth',
            name='location',
            field=models.CharField(choices=[('이해랑예술극장', '이해랑예술극장'), ('사회과학관', '사회과학관'), ('혜화관', '혜화관'), ('혜화별관', '혜화별관'), ('명진관', '명진관'), ('팔정도', '팔정도'), ('원흥관 4층', '원흥관 4층'), ('만해광장', '만해광장'), ('학생회관', '학생회관'), ('학림관', '학림관')], max_length=10),
        ),
    ]
