# Generated by Django 4.1 on 2023-05-20 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0012_booth_section_alter_booth_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='section',
            field=models.CharField(max_length=5),
        ),
    ]
