# Generated by Django 4.2.1 on 2023-05-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booth", "0014_alter_booth_section_alter_booth_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booth",
            name="section",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
