# Generated by Django 4.2.1 on 2023-05-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booth", "0016_alter_booth_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booth",
            name="section",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
